production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_rsa_domain: <%= ENV["AUTH0AUTH0_RSA_DOMAIN"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_rsa_domain: <%= ENV["AUTH0_RSA_DOMAIN"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>
  auth0_client_id: <%= ENV["AUTH0_CLIENT_ID"] %>
  auth0_client_secret: <%= ENV["AUTH0_CLIENT_SECRET"] %>
  auth0_rsa_domain: <%= ENV["AUTH0_RSA_DOMAIN"] %>
